name: Mirror Changes

on:
  workflow_dispatch:
    inputs:
      source_repository:
        description: 'Repo-3'
        required: true

jobs:
  mirror_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo-3 repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.source_repository }}

      - name: Push changes to Repo-5 repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://github.com/muram-105/Repo-5.git
          cd Repo-5
          cp -R ../Repo-3/* .
          git add .
          git commit -m "Mirror changes"
          git push
