name: Sync Changes

on:
  push:
    branches:
      - main

jobs:
  sync_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Second Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "muram-105"
          git config user.email "muram8700@gmail.com"

      - name: Clone First Repository
        run: |
          git clone https://github.com/muram-105/Repo3.git
          cd Repo3
          git checkout main

      - name: Sync Changes from First Repository
        run: |
          cd Repo3
          git pull
          cd ..
          rsync -avh --delete Repo3/ Repo-5/

      - name: Commit and Push Changes to Second Repository
        run: |
          cd Repo-5
          git add -A
          git commit -m "Sync changes from first repository"
          git push origin main
